
data:
    name: cifar-10 
    datapath: Datasets
    url: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
    classes: 10
    height: 28
    width: 28
    channels: 3
    #labels: DEFAULT -> range(0,classes)

models_to_run: model1, model2

model1:
    outpath: saved_models/model1
    layers: conv2d, conv2d, conv2d, conv2d
    batch_size: 128
    epochs: -1
    validation_split: 0.2

model2:
    #outpath: DEFAULT -> 'dataset'/saved_models/model2
    #batch_size: DEFAULT -> 128
    #epochs: DEFAULT -> -1
    #validation_split: DEFAULT-> 0.2
    layers: conv2d, conv2d, conv2d, conv2d_4rot

